use crate::models::SearchResultItem;

pub fn get_system_commands() -> Vec<SearchResultItem> {
    vec![
        SearchResultItem {
            id: "sys-clipboard".to_string(),
            title: "Clipboard History".to_string(),
            subtitle: Some("Search and paste from clipboard over time".to_string()),
            icon: None,
            icon_data: None, // We can add SVG strings here later or let frontend handle it
            item_type: "core_command".to_string(),
            action_data: "switch_view_clipboard".to_string(),
            score: 0,
        },
        SearchResultItem {
            id: "sys-sleep".to_string(),
            title: "Sleep".to_string(),
            subtitle: Some("Suspend the system".to_string()),
            icon: None,
            icon_data: None, // We can add SVG strings here later or let frontend handle it
            item_type: "system".to_string(),
            action_data: "systemctl suspend".to_string(),
            score: 0,
        },
        SearchResultItem {
            id: "sys-lock".to_string(),
            title: "Lock Screen".to_string(),
            subtitle: Some("Lock the current session".to_string()),
            icon: None,
            icon_data: None,
            item_type: "system".to_string(),
            action_data: "loginctl lock-session".to_string(),
            score: 0,
        },
        SearchResultItem {
            id: "sys-shutdown".to_string(),
            title: "Shutdown".to_string(),
            subtitle: Some("Turn off the computer".to_string()),
            icon: None,
            icon_data: None,
            item_type: "system".to_string(),
            action_data: "systemctl poweroff".to_string(),
            score: 0,
        },
        SearchResultItem {
            id: "sys-restart".to_string(),
            title: "Restart".to_string(),
            subtitle: Some("Reboot the computer".to_string()),
            icon: None,
            icon_data: None,
            item_type: "system".to_string(),
            action_data: "systemctl reboot".to_string(),
            score: 0,
        },
        SearchResultItem {
            id: "sys-vol-up".to_string(),
            title: "Volume Up".to_string(),
            subtitle: Some("Increase audio volume by 5%".to_string()),
            icon: None,
            icon_data: None,
            item_type: "system".to_string(),
            action_data: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+".to_string(),
            score: 0,
        },
        SearchResultItem {
            id: "sys-vol-down".to_string(),
            title: "Volume Down".to_string(),
            subtitle: Some("Decrease audio volume by 5%".to_string()),
            icon: None,
            icon_data: None,
            item_type: "system".to_string(),
            action_data: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-".to_string(),
            score: 0,
        },
        SearchResultItem {
            id: "sys-mute".to_string(),
            title: "Toggle Mute".to_string(),
            subtitle: Some("Mute or unmute audio".to_string()),
            icon: None,
            icon_data: None,
            item_type: "system".to_string(),
            action_data: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle".to_string(),
            score: 0,
        },
    ]
}
